name: Move Linked Issues

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      project_name_prefix: ${{ steps.format_date.outputs.formatted_date }}
    steps:
      - name: Get PR creation date
        id: format_date
        run: |
          # Extract the month and year from the PR creation date
          PR_DATE="${{ github.event.pull_request.created_at }}"
          FORMATTED_DATE=$(date -d "$PR_DATE" "+%B %Y")  # Format to Month Year
          echo "formatted_date=${FORMATTED_DATE} Sprint"
          echo "formatted_date=${FORMATTED_DATE} Sprint" >> $GITHUB_ENV  # Set the formatted date to an environment variable
          echo "project_name_prefix=${FORMATTED_DATE} Sprint" >> "$GITHUB_OUTPUT"  # Set the project name prefix to an environment variable

  debug-date:
    needs: get-date
    runs-on: ubuntu-latest
    steps:
      - name: debug        
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Project Column Name: Review"
          #echo "Project Name Prefix: ${{ steps.format_date.outputs.project_name_prefix }}"
          echo "Project Name Prefix (from output): ${{ steps.format_date.outputs.formatted_date }}"
          echo "Debug - Output file content:"
          cat "$GITHUB_OUTPUT"  # This will show the contents of $GITHUB_OUTPUT

  move-issues:
    needs: get-date
    uses: TransactionProcessing/org-ci-workflows/.github/workflows/move-linked-issue.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      project_column_name: "Review"
      project_name_prefix: ${{ needs.get-date.outputs.project_name_prefix }}  # Access the output from get-date job
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
