name: Use Reusable Job - Create Shared Nuget Update Issue

on:
  repository_dispatch:

jobs:
  create-shared-issue:
    #uses: org-ci-workflows/.github/workflows/reusable-create-shared-issue.yml@main
    uses: TransactionProcessing/org-ci-workflows/.github/workflows/reusable-create-shared-issue.yml@main
    with:
      issue-title: "Update Shared Nugets"
      issue-body: "Version Number xyz is now available"
      target-repos: "TransactionProcessing/Testing"
      project-org: "TransactionProcessing"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}      
